### ISSUE TITLE
Why not SDC?

### ISSUE THREAD

**Issue by Juburin** [drupalninja/drupalx_theme#1]
This looks like a really cool project.
I'm just wondering why you aren't using single directory components, since the setup is already almost matching?
SDC is moving into Drupal Core with 10.3 and there are modules for the mapping with storybook.
I'm excited to see more of this!

**Comment by nextagencyio** [comment]
> This looks like a really cool project. I'm just wondering why you aren't using single directory components, since the setup is already almost matching? SDC is moving into Drupal Core with 10.3 and there are modules for the mapping with storybook. I'm excited to see more of this!

Ya I am open to it for sure, it just seems somewhat redundant with Storybook. I think it would be easy enough to create the yaml for each component then rework it a little bit to use the different syntax to pull in the component and I need to figure out how libraries are supposed to be attached using this method.

**Comment by nextagencyio** [comment]
PR: https://github.com/drupalninja/drupalx_theme/pull/4
